
DROP TABLE IF EXISTS ADMISSIONS;
CREATE TABLE ADMISSIONS (	-- rows=58976
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   ADMITTIME DATETIME2(0) NOT NULL,
   DISCHTIME DATETIME2(0) NOT NULL,
   DEATHTIME DATETIME2(0),
   ADMISSION_TYPE VARCHAR(255) NOT NULL,	-- max=9
   ADMISSION_LOCATION VARCHAR(255) NOT NULL,	-- max=25
   DISCHARGE_LOCATION VARCHAR(255) NOT NULL,	-- max=25
   INSURANCE VARCHAR(255) NOT NULL,	-- max=10
   LANGUAGE VARCHAR(255),	-- max=4
   RELIGION VARCHAR(255),	-- max=22
   MARITAL_STATUS VARCHAR(255),	-- max=17
   ETHNICITY VARCHAR(255) NOT NULL,	-- max=56
   EDREGTIME DATETIME2(0),
   EDOUTTIME DATETIME2(0),
   DIAGNOSIS VARCHAR(max),	-- max=189
   HOSPITAL_EXPIRE_FLAG SMALLINT CHECK (HOSPITAL_EXPIRE_FLAG > 0) NOT NULL,
   HAS_CHARTEVENTS_DATA SMALLINT CHECK (HAS_CHARTEVENTS_DATA > 0) NOT NULL,
  CONSTRAINT ADMISSIONS_ROW_ID UNIQUE (ROW_ID),	-- nvals=58976
  CONSTRAINT ADMISSIONS_HADM_ID UNIQUE (HADM_ID)	-- nvals=58976
  );



DROP TABLE IF EXISTS CALLOUT;
CREATE TABLE CALLOUT (	-- rows=34499
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   SUBMIT_WARDID SMALLINT CHECK (SUBMIT_WARDID > 0),
   SUBMIT_CAREUNIT VARCHAR(255),	-- max=5
   CURR_WARDID SMALLINT CHECK (CURR_WARDID > 0),
   CURR_CAREUNIT VARCHAR(255),	-- max=5
   CALLOUT_WARDID SMALLINT CHECK (CALLOUT_WARDID > 0) NOT NULL,
   CALLOUT_SERVICE VARCHAR(255) NOT NULL,	-- max=5
   REQUEST_TELE SMALLINT CHECK (REQUEST_TELE > 0) NOT NULL,
   REQUEST_RESP SMALLINT CHECK (REQUEST_RESP > 0) NOT NULL,
   REQUEST_CDIFF SMALLINT CHECK (REQUEST_CDIFF > 0) NOT NULL,
   REQUEST_MRSA SMALLINT CHECK (REQUEST_MRSA > 0) NOT NULL,
   REQUEST_VRE SMALLINT CHECK (REQUEST_VRE > 0) NOT NULL,
   CALLOUT_STATUS VARCHAR(255) NOT NULL,	-- max=8
   CALLOUT_OUTCOME VARCHAR(255) NOT NULL,	-- max=10
   DISCHARGE_WARDID SMALLINT CHECK (DISCHARGE_WARDID > 0),
   ACKNOWLEDGE_STATUS VARCHAR(255) NOT NULL,	-- max=14
   CREATETIME DATETIME2(0) NOT NULL,
   UPDATETIME DATETIME2(0) NOT NULL,
   ACKNOWLEDGETIME DATETIME2(0),
   OUTCOMETIME DATETIME2(0) NOT NULL,
   FIRSTRESERVATIONTIME DATETIME2(0),
   CURRENTRESERVATIONTIME DATETIME2(0),
  CONSTRAINT CALLOUT_ROW_ID UNIQUE (ROW_ID),	-- nvals=34499
  -- CONSTRAINT CALLOUT_CURRENTRESERVATIONTIME UNIQUE (CURRENTRESERVATIONTIME)	-- nvals=1164
  );

DROP TABLE IF EXISTS CAREGIVERS;
CREATE TABLE CAREGIVERS (	-- rows=7567
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   CGID SMALLINT CHECK (CGID > 0) NOT NULL,
   LABEL VARCHAR(255),	-- max=6
   DESCRIPTION VARCHAR(255),	-- max=21
  CONSTRAINT CAREGIVERS_ROW_ID UNIQUE (ROW_ID),	-- nvals=7567
  CONSTRAINT CAREGIVERS_CGID UNIQUE (CGID)	-- nvals=7567
  );


DROP TABLE IF EXISTS CHARTEVENTS;
CREATE TABLE CHARTEVENTS (	-- rows=263201375
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0),
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0),
   ITEMID INT CHECK (ITEMID > 0) NOT NULL,
   CHARTTIME DATETIME2(0) NOT NULL,
   STORETIME DATETIME2(0),
   CGID SMALLINT CHECK (CGID > 0),
   VALUE VARCHAR(max),	-- max=91
   VALUENUM FLOAT,
   VALUEUOM VARCHAR(255),	-- max=17
   WARNING SMALLINT CHECK (WARNING > 0),
   ERROR SMALLINT CHECK (ERROR > 0),
   RESULTSTATUS VARCHAR(255),	-- max=6
   STOPPED VARCHAR(255),	-- max=8
  CONSTRAINT CHARTEVENTS_ROW_ID UNIQUE (ROW_ID)	-- nvals=263201375
  );

DROP TABLE IF EXISTS CPTEVENTS;
CREATE TABLE CPTEVENTS (	-- rows=573146
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   COSTCENTER VARCHAR(255) NOT NULL,	-- max=4
   CHARTDATE DATETIME2(0),
   CPT_CD VARCHAR(255) NOT NULL,	-- max=5
   CPT_NUMBER INT CHECK (CPT_NUMBER > 0),
   CPT_SUFFIX VARCHAR(255),	-- max=1
   TICKET_ID_SEQ SMALLINT CHECK (TICKET_ID_SEQ > 0),
   SECTIONHEADER VARCHAR(255),	-- max=25
   SUBSECTIONHEADER VARCHAR(max),	-- max=169
   DESCRIPTION VARCHAR(255),	-- max=30
  CONSTRAINT CPTEVENTS_ROW_ID UNIQUE (ROW_ID)	-- nvals=573146
  );


DROP TABLE IF EXISTS DATETIMEEVENTS;
CREATE TABLE DATETIMEEVENTS (	-- rows=4486049
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0),
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0),
   ITEMID INT CHECK (ITEMID > 0) NOT NULL,
   CHARTTIME DATETIME2(0) NOT NULL,
   STORETIME DATETIME2(0) NOT NULL,
   CGID SMALLINT CHECK (CGID > 0) NOT NULL,
   VALUE DATETIME2(0),
   VALUEUOM VARCHAR(255) NOT NULL,	-- max=13
   WARNING SMALLINT CHECK (WARNING > 0),
   ERROR SMALLINT CHECK (ERROR > 0),
   RESULTSTATUS VARCHAR(255),	-- max=0
   STOPPED VARCHAR(255),	-- max=8
  CONSTRAINT DATETIMEEVENTS_ROW_ID UNIQUE (ROW_ID)	-- nvals=4486049
  );


DROP TABLE IF EXISTS DIAGNOSES_ICD;
CREATE TABLE DIAGNOSES_ICD (	-- rows=651047
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   SEQ_NUM SMALLINT CHECK (SEQ_NUM > 0),
   ICD9_CODE VARCHAR(255),	-- max=5
  CONSTRAINT DIAGNOSES_ICD_ROW_ID UNIQUE (ROW_ID)	-- nvals=651047
  );


DROP TABLE IF EXISTS DRGCODES;
CREATE TABLE DRGCODES (	-- rows=125557
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   DRG_TYPE VARCHAR(255) NOT NULL,	-- max=4
   DRG_CODE VARCHAR(255) NOT NULL,	-- max=4
   DESCRIPTION VARCHAR(max),	-- max=193
   DRG_SEVERITY SMALLINT CHECK (DRG_SEVERITY > 0),
   DRG_MORTALITY SMALLINT CHECK (DRG_MORTALITY > 0),
  CONSTRAINT DRGCODES_ROW_ID UNIQUE (ROW_ID)	-- nvals=125557
  );

DROP TABLE IF EXISTS D_CPT;
CREATE TABLE D_CPT (	-- rows=134
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   CATEGORY SMALLINT CHECK (CATEGORY > 0) NOT NULL,
   SECTIONRANGE VARCHAR(255) NOT NULL,	-- max=37
   SECTIONHEADER VARCHAR(255) NOT NULL,	-- max=25
   SUBSECTIONRANGE VARCHAR(255) NOT NULL,	-- max=11
   SUBSECTIONHEADER VARCHAR(max) NOT NULL,	-- max=169
   CODESUFFIX VARCHAR(255),	-- max=1
   MINCODEINSUBSECTION INT CHECK (MINCODEINSUBSECTION > 0) NOT NULL,
   MAXCODEINSUBSECTION INT CHECK (MAXCODEINSUBSECTION > 0) NOT NULL,
  CONSTRAINT D_CPT_ROW_ID UNIQUE (ROW_ID),	-- nvals=134
  CONSTRAINT D_CPT_SUBSECTIONRANGE UNIQUE (SUBSECTIONRANGE),	-- nvals=134
  CONSTRAINT D_CPT_MAXCODEINSUBSECTION UNIQUE (MAXCODEINSUBSECTION)	-- nvals=134
  );



DROP TABLE IF EXISTS D_ICD_DIAGNOSES;
CREATE TABLE D_ICD_DIAGNOSES (	-- rows=14567
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   ICD9_CODE VARCHAR(255) NOT NULL,	-- max=5
   SHORT_TITLE VARCHAR(255) NOT NULL,	-- max=24
   LONG_TITLE VARCHAR(max) NOT NULL,	-- max=222
  CONSTRAINT D_ICD_DIAGNOSES_ROW_ID UNIQUE (ROW_ID),	-- nvals=14567
  CONSTRAINT D_ICD_DIAGNOSES_ICD9_CODE UNIQUE (ICD9_CODE)	-- nvals=14567
  );



DROP TABLE IF EXISTS D_ICD_PROCEDURES;
CREATE TABLE D_ICD_PROCEDURES (	-- rows=3882
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   ICD9_CODE VARCHAR(255) NOT NULL,	-- max=4
   SHORT_TITLE VARCHAR(255) NOT NULL,	-- max=24
   LONG_TITLE VARCHAR(max) NOT NULL,	-- max=163
  CONSTRAINT D_ICD_PROCEDURES_ROW_ID UNIQUE (ROW_ID),	-- nvals=3882
  CONSTRAINT D_ICD_PROCEDURES_ICD9_CODE UNIQUE (ICD9_CODE),	-- nvals=3882
  CONSTRAINT D_ICD_PROCEDURES_SHORT_TITLE UNIQUE (SHORT_TITLE)	-- nvals=3882
  );


DROP TABLE IF EXISTS D_ITEMS;
CREATE TABLE D_ITEMS (	-- rows=12478
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   ITEMID INT CHECK (ITEMID > 0) NOT NULL,
   LABEL VARCHAR(max),	-- max=95
   ABBREVIATION VARCHAR(255),	-- max=50
   DBSOURCE VARCHAR(255) NOT NULL,	-- max=10
   LINKSTO VARCHAR(255),	-- max=18
   CATEGORY VARCHAR(255),	-- max=27
   UNITNAME VARCHAR(255),	-- max=19
   PARAM_TYPE VARCHAR(255),	-- max=16
   CONCEPTID VARCHAR(255),	-- max=0
  CONSTRAINT D_ITEMS_ROW_ID UNIQUE (ROW_ID),	-- nvals=12478
  CONSTRAINT D_ITEMS_ITEMID UNIQUE (ITEMID)	-- nvals=12478
  );


DROP TABLE IF EXISTS D_LABITEMS;
CREATE TABLE D_LABITEMS (	-- rows=755
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   ITEMID INT CHECK (ITEMID > 0) NOT NULL,
   LABEL VARCHAR(255) NOT NULL,	-- max=36
   FLUID VARCHAR(255) NOT NULL,	-- max=25
   CATEGORY VARCHAR(255) NOT NULL,	-- max=10
   LOINC_CODE VARCHAR(255),	-- max=7
  CONSTRAINT D_LABITEMS_ROW_ID UNIQUE (ROW_ID),	-- nvals=755
  CONSTRAINT D_LABITEMS_ITEMID UNIQUE (ITEMID)	-- nvals=755
  );


DROP TABLE IF EXISTS ICUSTAYS;
CREATE TABLE ICUSTAYS (	-- rows=61532
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0) NOT NULL,
   DBSOURCE VARCHAR(255) NOT NULL,	-- max=10
   FIRST_CAREUNIT VARCHAR(255) NOT NULL,	-- max=5
   LAST_CAREUNIT VARCHAR(255) NOT NULL,	-- max=5
   FIRST_WARDID SMALLINT CHECK (FIRST_WARDID > 0) NOT NULL,
   LAST_WARDID SMALLINT CHECK (LAST_WARDID > 0) NOT NULL,
   INTIME DATETIME2(0) NOT NULL,
   OUTTIME DATETIME2(0),
   LOS FLOAT,
  CONSTRAINT ICUSTAYS_ROW_ID UNIQUE (ROW_ID),	-- nvals=61532
  CONSTRAINT ICUSTAYS_ICUSTAY_ID UNIQUE (ICUSTAY_ID)	-- nvals=61532
  );


DROP TABLE IF EXISTS INPUTEVENTS_CV;
CREATE TABLE INPUTEVENTS_CV (	-- rows=17528894
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID SMALLINT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0),
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0),
   CHARTTIME DATETIME2(0) NOT NULL,
   ITEMID SMALLINT CHECK (ITEMID > 0) NOT NULL,
   AMOUNT FLOAT,
   AMOUNTUOM VARCHAR(255),	-- max=3
   RATE FLOAT,
   RATEUOM VARCHAR(255),	-- max=8
   STORETIME DATETIME2(0) NOT NULL,
   CGID SMALLINT CHECK (CGID > 0),
   ORDERID INT CHECK (ORDERID > 0) NOT NULL,
   LINKORDERID INT CHECK (LINKORDERID > 0) NOT NULL,
   STOPPED VARCHAR(255),	-- max=8
   NEWBOTTLE SMALLINT CHECK (NEWBOTTLE > 0),
   ORIGINALAMOUNT FLOAT,
   ORIGINALAMOUNTUOM VARCHAR(255),	-- max=3
   ORIGINALROUTE VARCHAR(255),	-- max=20
   ORIGINALRATE FLOAT,
   ORIGINALRATEUOM VARCHAR(255),	-- max=5
   ORIGINALSITE VARCHAR(255),	-- max=20
  CONSTRAINT INPUTEVENTS_CV_ROW_ID UNIQUE (ROW_ID)	-- nvals=17528894
  );



DROP TABLE IF EXISTS INPUTEVENTS_MV;
CREATE TABLE INPUTEVENTS_MV (	-- rows=3618991
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0),
   STARTTIME DATETIME2(0) NOT NULL,
   ENDTIME DATETIME2(0) NOT NULL,
   ITEMID INT CHECK (ITEMID > 0) NOT NULL,
   AMOUNT FLOAT NOT NULL,
   AMOUNTUOM VARCHAR(255) NOT NULL,	-- max=19
   RATE FLOAT,
   RATEUOM VARCHAR(255),	-- max=12
   STORETIME DATETIME2(0) NOT NULL,
   CGID SMALLINT CHECK (CGID > 0) NOT NULL,
   ORDERID INT CHECK (ORDERID > 0) NOT NULL,
   LINKORDERID INT CHECK (LINKORDERID > 0) NOT NULL,
   ORDERCATEGORYNAME VARCHAR(255) NOT NULL,	-- max=24
   SECONDARYORDERCATEGORYNAME VARCHAR(255),	-- max=24
   ORDERCOMPONENTTYPEDESCRIPTION VARCHAR(255) NOT NULL,	-- max=57
   ORDERCATEGORYDESCRIPTION VARCHAR(255) NOT NULL,	-- max=14
   PATIENTWEIGHT FLOAT NOT NULL,
   TOTALAMOUNT FLOAT,
   TOTALAMOUNTUOM VARCHAR(255),	-- max=2
   ISOPENBAG SMALLINT CHECK (ISOPENBAG > 0) NOT NULL,
   CONTINUEINNEXTDEPT SMALLINT CHECK (CONTINUEINNEXTDEPT > 0) NOT NULL,
   CANCELREASON SMALLINT CHECK (CANCELREASON > 0) NOT NULL,
   STATUSDESCRIPTION VARCHAR(255) NOT NULL,	-- max=15
   COMMENTS_EDITEDBY VARCHAR(255),	-- max=15
   COMMENTS_CANCELEDBY VARCHAR(255),	-- max=15
   COMMENTS_DATE DATETIME2(0),
   ORIGINALAMOUNT FLOAT NOT NULL,
   ORIGINALRATE FLOAT NOT NULL,
  CONSTRAINT INPUTEVENTS_MV_ROW_ID UNIQUE (ROW_ID)	-- nvals=3618991
  );


DROP TABLE IF EXISTS LABEVENTS;
CREATE TABLE LABEVENTS (	-- rows=27872575
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0),
   ITEMID INT CHECK (ITEMID > 0) NOT NULL,
   CHARTTIME DATETIME2(0) NOT NULL,
   VALUE VARCHAR(max),	-- max=100
   VALUENUM FLOAT,
   VALUEUOM VARCHAR(255),	-- max=10
   FLAG VARCHAR(255),	-- max=8
  CONSTRAINT LABEVENTS_ROW_ID UNIQUE (ROW_ID)	-- nvals=27872575
  );


DROP TABLE IF EXISTS MICROBIOLOGYEVENTS;
CREATE TABLE MICROBIOLOGYEVENTS (	-- rows=328446
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0),
   CHARTDATE DATETIME2(0) NOT NULL,
   CHARTTIME DATETIME2(0),
   SPEC_ITEMID INT CHECK (SPEC_ITEMID > 0),
   SPEC_TYPE_DESC VARCHAR(255) NOT NULL,	-- max=56
   ORG_ITEMID INT CHECK (ORG_ITEMID > 0),
   ORG_NAME VARCHAR(255),	-- max=70
   ISOLATE_NUM SMALLINT CHECK (ISOLATE_NUM > 0),
   AB_ITEMID INT CHECK (AB_ITEMID > 0),
   AB_NAME VARCHAR(255),	-- max=20
   DILUTION_TEXT VARCHAR(255),	-- max=6
   DILUTION_COMPARISON VARCHAR(255),	-- max=2
   DILUTION_VALUE SMALLINT CHECK (DILUTION_VALUE > 0),
   INTERPRETATION VARCHAR(255),	-- max=1
  CONSTRAINT MICROBIOLOGYEVENTS_ROW_ID UNIQUE (ROW_ID)	-- nvals=328446
  );


DROP TABLE IF EXISTS NOTEEVENTS;
CREATE TABLE NOTEEVENTS (	-- rows=2078705
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0),
   CHARTDATE DATE NOT NULL,
   CHARTTIME DATETIME2(0),
   STORETIME DATETIME2(0),
   CATEGORY VARCHAR(255) NOT NULL,	-- max=17
   DESCRIPTION VARCHAR(255) NOT NULL,	-- max=80
   CGID SMALLINT CHECK (CGID > 0),
   ISERROR SMALLINT CHECK (ISERROR > 0),
   TEXT VARCHAR(max),	-- max=55725
  CONSTRAINT NOTEEVENTS_ROW_ID UNIQUE (ROW_ID)	-- nvals=2078705
  );


DROP TABLE IF EXISTS OUTPUTEVENTS;
CREATE TABLE OUTPUTEVENTS (	-- rows=4349339
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0),
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0),
   CHARTTIME DATETIME2(0) NOT NULL,
   ITEMID INT CHECK (ITEMID > 0) NOT NULL,
   VALUE FLOAT,
   VALUEUOM VARCHAR(255),	-- max=2
   STORETIME DATETIME2(0) NOT NULL,
   CGID SMALLINT CHECK (CGID > 0) NOT NULL,
   STOPPED VARCHAR(255),	-- max=0
   NEWBOTTLE VARCHAR(255),	-- max=0
   ISERROR VARCHAR(255),	-- max=0
  CONSTRAINT OUTPUTEVENTS_ROW_ID UNIQUE (ROW_ID)	-- nvals=4349339
  );


DROP TABLE IF EXISTS PATIENTS;
CREATE TABLE PATIENTS (	-- rows=46520
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   GENDER VARCHAR(255) NOT NULL,	-- max=1
   DOB VARCHAR(255) NOT NULL,	-- max=19
   DOD DATETIME2(0),
   DOD_HOSP DATETIME2(0),
   DOD_SSN DATETIME2(0),
   EXPIRE_FLAG SMALLINT CHECK (EXPIRE_FLAG > 0) NOT NULL,
  CONSTRAINT PATIENTS_ROW_ID UNIQUE (ROW_ID),	-- nvals=46520
  CONSTRAINT PATIENTS_SUBJECT_ID UNIQUE (SUBJECT_ID)	-- nvals=46520
  );


DROP TABLE IF EXISTS PRESCRIPTIONS;
CREATE TABLE PRESCRIPTIONS (	-- rows=4156848
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0),
   STARTDATE DATETIME2(0),
   ENDDATE DATETIME2(0),
   DRUG_TYPE VARCHAR(255) NOT NULL,	-- max=8
   DRUG VARCHAR(255),	-- max=58
   DRUG_NAME_POE VARCHAR(255),	-- max=58
   DRUG_NAME_GENERIC VARCHAR(255),	-- max=49
   FORMULARY_DRUG_CD VARCHAR(255),	-- max=17
   GSN VARCHAR(max),	-- max=125
   NDC VARCHAR(255),	-- max=11
   PROD_STRENGTH VARCHAR(255),	-- max=60
   DOSE_VAL_RX VARCHAR(255),	-- max=26
   DOSE_UNIT_RX VARCHAR(255),	-- max=32
   FORM_VAL_DISP VARCHAR(255),	-- max=47
   FORM_UNIT_DISP VARCHAR(255),	-- max=13
   ROUTE VARCHAR(255),	-- max=28
  CONSTRAINT PRESCRIPTIONS_ROW_ID UNIQUE (ROW_ID)	-- nvals=4156848
  );


DROP TABLE IF EXISTS PROCEDUREEVENTS_MV;
CREATE TABLE PROCEDUREEVENTS_MV (	-- rows=258066
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0),
   STARTTIME DATETIME2(0) NOT NULL,
   ENDTIME DATETIME2(0) NOT NULL,
   ITEMID INT CHECK (ITEMID > 0) NOT NULL,
   VALUE FLOAT NOT NULL,
   VALUEUOM VARCHAR(255) NOT NULL,	-- max=4
   LOCATION VARCHAR(255),	-- max=24
   LOCATIONCATEGORY VARCHAR(255),	-- max=19
   STORETIME DATETIME2(0) NOT NULL,
   CGID SMALLINT CHECK (CGID > 0) NOT NULL,
   ORDERID INT CHECK (ORDERID > 0) NOT NULL,
   LINKORDERID INT CHECK (LINKORDERID > 0) NOT NULL,
   ORDERCATEGORYNAME VARCHAR(255) NOT NULL,	-- max=21
   SECONDARYORDERCATEGORYNAME VARCHAR(255),	-- max=0
   ORDERCATEGORYDESCRIPTION VARCHAR(255) NOT NULL,	-- max=12
   ISOPENBAG SMALLINT CHECK (ISOPENBAG > 0) NOT NULL,
   CONTINUEINNEXTDEPT SMALLINT CHECK (CONTINUEINNEXTDEPT > 0) NOT NULL,
   CANCELREASON SMALLINT CHECK (CANCELREASON > 0) NOT NULL,
   STATUSDESCRIPTION VARCHAR(255) NOT NULL,	-- max=15
   COMMENTS_EDITEDBY VARCHAR(255),	-- max=7
   COMMENTS_CANCELEDBY VARCHAR(255),	-- max=17
   COMMENTS_DATE DATETIME2(0),
  CONSTRAINT PROCEDUREEVENTS_MV_ROW_ID UNIQUE (ROW_ID),	-- nvals=258066
  CONSTRAINT PROCEDUREEVENTS_MV_ORDERID UNIQUE (ORDERID)	-- nvals=258066
  );


DROP TABLE IF EXISTS PROCEDURES_ICD;
CREATE TABLE PROCEDURES_ICD (	-- rows=240095
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   SEQ_NUM SMALLINT CHECK (SEQ_NUM > 0) NOT NULL,
   ICD9_CODE VARCHAR(255) NOT NULL,	-- max=4
  CONSTRAINT PROCEDURES_ICD_ROW_ID UNIQUE (ROW_ID)	-- nvals=240095
  );


DROP TABLE IF EXISTS SERVICES;
CREATE TABLE SERVICES (	-- rows=73343
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   TRANSFERTIME DATETIME2(0) NOT NULL,
   PREV_SERVICE VARCHAR(255),	-- max=5
   CURR_SERVICE VARCHAR(255) NOT NULL,	-- max=5
  CONSTRAINT SERVICES_ROW_ID UNIQUE (ROW_ID)	-- nvals=73343
  );



DROP TABLE IF EXISTS TRANSFERS;
CREATE TABLE TRANSFERS (	-- rows=261897
   ROW_ID INT CHECK (ROW_ID > 0) NOT NULL,
   SUBJECT_ID INT CHECK (SUBJECT_ID > 0) NOT NULL,
   HADM_ID INT CHECK (HADM_ID > 0) NOT NULL,
   ICUSTAY_ID INT CHECK (ICUSTAY_ID > 0),
   DBSOURCE VARCHAR(255),	-- max=10
   EVENTTYPE VARCHAR(255),	-- max=9
   PREV_CAREUNIT VARCHAR(255),	-- max=5
   CURR_CAREUNIT VARCHAR(255),	-- max=5
   PREV_WARDID SMALLINT CHECK (PREV_WARDID > 0),
   CURR_WARDID SMALLINT CHECK (CURR_WARDID > 0),
   INTIME DATETIME2(0),
   OUTTIME DATETIME2(0),
   LOS FLOAT,
  CONSTRAINT TRANSFERS_ROW_ID UNIQUE (ROW_ID)	-- nvals=261897
  );





